# Generated by Django 6.0.7 on 2026-07-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
    ]
