# Generated by Django 6.0.7 on 2026-07-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0002_mcq_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='is_exam_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='master_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
