# Generated by Django 6.0.7 on 2026-07-24 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0004_userchaptermastery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='stream',
            field=models.CharField(choices=[('PRE_ENG', 'Pre-Engineering'), ('PRE_MED', 'Pre-Medical'), ('BOTH', 'both')], default='BOTH', max_length=10),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(choices=[('PRE_ENG', 'Pre-Engineering'), ('PRE_MED', 'Pre-Medical')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
