# Generated by Django 6.0.7 on 2026-07-25 12:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchaptermastery',
            name='date_taken',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
