# Generated by Django 6.0.7 on 2026-07-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0008_userchaptermastery_date_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='weightage',
            field=models.IntegerField(default=1),
        ),
    ]
