# Generated by Django 6.0.7 on 2026-07-27 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0009_alter_chapter_weightage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='ZehnifyApp.subject'),
        ),
        migrations.AlterField(
            model_name='chaptervideo',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='ZehnifyApp.chapter'),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='ZehnifyApp.chapter'),
        ),
    ]
