# Generated by Django 6.0.7 on 2026-07-27 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0010_alter_chapter_subject_alter_chaptervideo_chapter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaptervideo',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='chaptervideo',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chaptervideo',
            name='title',
            field=models.CharField(default='Untitled Lecture', max_length=200),
        ),
        migrations.AlterField(
            model_name='chaptervideo',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='ZehnifyApp.chapter'),
        ),
        migrations.AlterField(
            model_name='chaptervideo',
            name='video_id',
            field=models.CharField(help_text="YouTube Video ID (e.g., 'dQw4w9WgXcQ')", max_length=50),
        ),
    ]
