# Generated by Django 6.0.7 on 2026-07-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0011_alter_chaptervideo_options_chaptervideo_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptervideo',
            name='video_id',
            field=models.CharField(help_text='Paste YouTube Video ID or full link', max_length=200),
        ),
    ]
