# Generated by Django 6.0.7 on 2026-07-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0013_videoprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaptervideo',
            old_name='video_id',
            new_name='url_path',
        ),
    ]
