# Generated by Django 6.0.7 on 2026-08-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0015_examattempt_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchaptermastery',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
