# Generated by Django 6.0.7 on 2026-08-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0016_userchaptermastery_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='diagram',
            field=models.ImageField(blank=True, null=True, upload_to='mcq_diagrams/'),
        ),
    ]
