# Generated by Django 6.0.7 on 2026-08-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0017_mcq_diagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq',
            name='difficulty',
        ),
    ]
