# Generated by Django 6.0.7 on 2026-08-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0019_alter_chapter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='grade',
            field=models.IntegerField(choices=[(11, '11th Grade'), (12, '12th Grade')], default=11),
        ),
    ]
