# Generated by Django 6.0.7 on 2026-08-13 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0020_chapter_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=10, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('is_bookmarked', models.BooleanField(default=False, help_text='Mark as an error or for future review')),
                ('last_attempted', models.DateTimeField(auto_now=True)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ZehnifyApp.mcq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mcq')},
            },
        ),
    ]
