# Generated by Django 6.0.7 on 2026-08-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0021_mcqattempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcq',
            old_name='is_exam_question',
            new_name='exam_question',
        ),
    ]
