# Generated by Django 6.0.7 on 2026-08-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0022_rename_is_exam_question_mcq_exam_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcq',
            old_name='exam_question',
            new_name='exam_questions',
        ),
    ]
