# Generated by Django 6.0.7 on 2026-08-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0023_rename_exam_question_mcq_exam_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcq',
            old_name='exam_questions',
            new_name='is_exam_question',
        ),
    ]
