# Generated by Django 6.0.7 on 2026-09-14 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0025_alter_chapter_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulas', models.TextField(blank=True, help_text='Supports LaTeX syntax for math symbols')),
                ('reminders', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='ZehnifyApp.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'chapter')},
            },
        ),
    ]
