# Generated by Django 6.0.7 on 2026-09-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0026_chapternote'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='key_formulas',
            field=models.TextField(blank=True, help_text='Enter LaTeX formulas, one per line (e.g., \\sqrt{4} or \x0crac{a}{b})', null=True),
        ),
    ]
