# Generated by Django 6.1.1 on 2026-09-28 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0027_chapter_key_formulas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='ZehnifyApp.chapter'),
        ),
    ]
