# Generated by Django 6.1.1 on 2026-09-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0028_alter_mcq_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='subtopic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
