# Generated by Django 6.1.1 on 2026-10-03 06:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0029_mcq_subtopic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='key_formulas',
            field=models.TextField(blank=True, help_text='Enter LaTeX formulas, one per line (e.g., \\sqrt{4} or \\frac{a}{b})', null=True),
        ),
        migrations.CreateModel(
            name='MixedPracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('date_taken', models.DateTimeField(default=django.utils.timezone.now)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZehnifyApp.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mixed_practice_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MixedPracticeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('selected_option', models.CharField(blank=True, max_length=10, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZehnifyApp.mcq')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ZehnifyApp.mixedpracticeattempt')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
