# Generated by Django 6.1.1 on 2026-10-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0030_alter_chapter_key_formulas_mixedpracticeattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptervideo',
            name='subtopic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
