# Generated by Django 6.1.1 on 2026-10-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0032_subtopicpracticeattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqattempt',
            name='mistake_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mcqattempt',
            name='reflection',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='mcqattempt',
            name='is_bookmarked',
            field=models.BooleanField(default=False, help_text="True = this question is in the student's My Mistakes log"),
        ),
    ]
