# Generated by Django 6.1.1 on 2026-10-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZehnifyApp', '0033_mcqattempt_mistake_type_mcqattempt_reflection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
